export const LOADING = '[ADMIN] LOADING'
export const ALL_CONTRACTS = '[ADMIN] ALL_CONTRACTS'
export const PURCHASED_CONTRACTS = '[ADMIN] PURCHASED_CONTRACTS'
export const PENDING_CONTRACTS = '[ADMIN] PENDING_CONTRACTS'
